name: C++ CI

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-latest, ubuntu-latest, macos-latest]
        include: 
        - os: macos-latest
          COMPILER: clang
          LINKER: clang       

        - os: ubuntu-latest
          COMPILER: gcc-9
          LINKER: gcc-9       

        - os: ubuntu-latest
          COMPILER: gcc-8
          LINKER: gcc-8
    
    steps:
    - uses: actions/checkout@v2
    - name: build cmake
      run: |
        mkdir build
        cmake /build
    - name: make
      run: make /build
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
